### ISSUE TITLE
default stage not working

### ISSUE THREAD

**Issue by huanzhang** [endoze/mina-multistage#10]
=====config/deploy.rb =====
set default_stage, 'test'
require 'mina/multistage'
require 'mina/bundler'
require 'mina/rails'
require 'mina/git'
...
...

config/deploy
├── production.rb
├── qa.rb
├── stage.rb
└── test.rb

run mina deply I got:

mina aborted!
Mina::Error: Setting :domain is not set
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/settings.rb:17:in `method_missing'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/helpers.rb:308:in `method_missing'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/ssh_helpers.rb:51:in `ssh_command'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/ssh_helpers.rb:89:in `invoke'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/ssh_helpers.rb:36:in `ssh'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/helpers.rb:57:in `block in run!'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/helpers.rb:84:in `measure'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/helpers.rb:73:in `report_time'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/helpers.rb:57:in `run!'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/lib/mina/helpers.rb:94:in `mina_cleanup!'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/bin/mina:55:in `block (2 levels) in <top (required)>'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/bin/mina:26:in `block in <top (required)>'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/bin/mina:25:in `instance_eval'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/gems/mina-0.3.2/bin/mina:25:in `<top (required)>'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/bin/mina:23:in `load'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/bin/mina:23:in `<main>'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/bin/ruby_executable_hooks:15:in `eval'
/Users/zhanghuan/.rvm/gems/ruby-2.1.5@hire/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by endoze** [comment]
Can you include the relevant stage files? 

Also, the syntax you are using to set the `default_stage` override is incorrect. I had shown in the readme example the wrong syntax, which I've fixed in #11.

**Comment by endoze** [comment]
@huanzhang Are you still having an issue? Is there anything I can do to help?

**Comment by huanzhang** [comment]
@endoze thanks for your replay. It is working now with ":".

**Comment by endoze** [comment]
I'm glad that fixed your issue.
