### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lymecca** [endoze/mina-multistage#14]
One question...

The migration from mina gem to mina-multistage gem is simple? I need to remove the mina gem first?

Note.: actually I have this gems configured: 
gem 'mina'
gem 'mina-unicorn', :require => false

**Comment by endoze** [comment]
You don't remove the `mina` gem from your project. `mina-multistage` doesn't replace `mina`, rather it is a plugin to add support for multiple stages to a project already using mina.

**Comment by lymecca** [comment]
Ok tks endoze
