### ISSUE TITLE
Question: is this plugin compatible with mina 1.0?

### ISSUE THREAD

**Issue by kritop** [endoze/mina-multistage#19]
i running into an error executing `mina deploy`, and wanted to know if its a compatibility issue or another problem

**Comment by endoze** [comment]
I'll have to check it out as I haven't upgraded any of my apps to use mina 1.0 as of yet. If you can post the error you are receiving it could make debugging any potential issues with this plugin much easier.

**Comment by kritop** [comment]
thanks!
also just ran into this: https://github.com/mina-deploy/mina/issues/62
does the plugin offer any more features that might consider using it over the default multistage support?

**Comment by endoze** [comment]
It avoids the `to=` syntax of setting the stage when deploying and uses a task instead. I personally like the syntax of `mina production deploy` over `mina deploy to=production`.

The other big difference is that this plugin allows storing your configuration for each stage in separate files and avoids stuffing a case/if statement in your `deploy.rb` configuration. 

The built in support for multistage is really great, this just builds on the same kind of idea with more separation of stage logic.

**Comment by endoze** [comment]
@kritop A heads up that I've just released a new version of this gem that is compatible with mina 1.0. The new version of mina-multistage is 1.0.3. Unless you have any further questions, I'm going to close this issue out. Thanks for your contributions!
