### ISSUE TITLE
Revert 1.0.3 and release 2.0

### ISSUE THREAD

**Issue by aried3r** [endoze/mina-multistage#23]
The change from 1.0.2 to 1.0.3 broke compatibility with mina 0.3.x which is a breaking change in a patch release.
I guess this project does not yet adhere to http://semver.org but it would be awesome if this breaking change was in a new major version.

My suggestion would be, revert 1.0.3 (maybe release 1.0.4 or 1.1) and then release the current 1.0.3 as 2.0. What do you think?

**Comment by endoze** [comment]
@aried3r While I do try to follow semver to the best of my abilities, I was unaware that this change broke compatibility with mina 0.3.x. What exactly broke with that version?

**Comment by endoze** [comment]
@aried3r I'm not sure what was broke. I'm going to close this issue out, but if there is indeed something that is broken, please re-open this issue and let me know. Thanks for your contribution!
